language: php

php:
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""
matrix:
  exclude:
  - php: 7.2
    env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - travis_retry composer dumpautoload -o

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover